<?php
/**
 * Created by PhpStorm.
 * User: xjyplayer
 * Date: 2018/11/27
 * Time: 20:39
 */

namespace app\api\controller\v1;

use app\api\controller\AuthBase;
use app\api\controller\Common;

class Comment extends AuthBase
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    public function read()
    {
        $data = request()->get();
    }

    public function save()
    {
        $data = request()->post();
        //验证
        $validate = Validate('Comment');
        if(!$validate->scene('add')->check($data)) {
            return httpResult(config("app.result_error"), $validate->getError(), [], 403);
        }
        //判断新闻是否存在
        try{
            $res = model("common/News") ->get($data["id"]);
        }catch(\Exception $e){
            Exception($e->getFile().$e->getLine().$e->getMessage());
        }
        if(empty($res)){
            return httpResult(config("app.result_error"),"新闻不存在" , [], 404);
        }

        //组装数据
        if(isset($data["to_user_id"])){
            try{
                $res = model("common/User") ->get($data["to_user_id"]);
            }catch(\Exception $e){
                Exception($e->getFile().$e->getLine().$e->getMessage());
            }
            if(empty($res)){
                return httpResult(config("app.result_error"),"该用户不存在" , [], 403);
            }
            $sdata["to_user_id"] = $data["to_user_id"];
        }
        if(isset($data["parent_id"])){
            try{
                $res = model("common/Comment") ->get($data["parent_id"]);
            }catch(\Exception $e){
                Exception($e->getFile().$e->getLine().$e->getMessage());
            }
            if(empty($res) || $res["status"] != 1){
                return httpResult(config("app.result_error"),"该评论已经被删除" , [],404 );
            }
            $sdata["parent_id"] = $data["parent_id"];
        }
        $sdata["news_id"] = $data["id"];
        $sdata["user_id"] = $this->user["id"];
        try{
            $res = model("common/Comment")->add($sdata);
        }catch(\Exception $e){
            Exception($e->getFile().$e->getLine().$e->getMessage());
        }
        if(empty($res)){
            return httpResult(config("app.result_error"),"评论失败" , [], 500);
        }
        return httpResult(config("app.result_ok"),"评论成功");
    }
}