<?php
/**
 * Created by PhpStorm.
 * User: xjyplayer
 * Date: 2018/11/24
 * Time: 22:30
 */

namespace app\api\controller\v1;

use app\api\controller\Common;

class Index extends Common
{
    private $mymodel;

    /**初始化
     * @throws \app\api\exception\APIException
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->mymodel = model("common/News");
    }


    /**获取首页推荐数据
     * @return \think\response\Json
     * @throws \Exception
     */
    public function Index()
    {
        try{
            $header = $this->mymodel->getIsHeadFigureNews();
            $position = $this->mymodel->getIsPositionNews();
        }catch(\Exception $e){
            Exception("获取数据出错");
        }
        //解析新闻种类
        $header = $this->parseCatid($header);
        $position = $this->parseCatid($position);

        $data = [
            "header" => $header,
            "position" => $position
        ];

        return httpResult(config("app.result_ok"),"",$data);
    }
}