<?php
/**
 * Created by PhpStorm.
 * User: xjyplayer
 * Date: 2018/11/25
 * Time: 13:02
 */

namespace app\api\controller\v1;

use app\api\controller\Common;
use app\api\exception\APIException;
use think\Exception;

class News extends Common
{
    /**对应的模型
     * @var
     */
    protected $myModel;

    /**初始化
     * @throws APIException
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->myModel = model("common/News");
    }

    /**新闻栏目信息获取
     * @param catid 需要获取的新闻种类
     * @param page 第几页内容，不传则为第一页
     * @param size 每页多大，不传则为默认分页大小
     * @throws APIException
     * @throws Exception
     * @return httpResult
     */
   public function read($catid)
   {
        //参数传递校验
        $data = request()->get();
        $data["catid"] = $catid;
        $validate = Validate('News');
        if(!$validate->scene('read')->check($data)){
            Exception($validate->getError());
        };
        if(empty($catid)){
            throw new APIException("请输入正确的新闻id");
        }
       //封装查询添加
       if(!empty($data["title"])){
           $sdata["title"] = ["like","%".$data["title"]."%"];
       }
       $sdata["catid"] = $data["catid"];
        //初始化分页参数
        try{
            $totalCount = $this->myModel->getNewsCountByCondition($sdata);
        }catch(\Exception $e){
            Exception($e->getMessage());
        }
        $this->initPaginateParams($totalCount);
        try{
            $newsInfo = $this->myModel->getNewsByCondition($sdata,$this->size,$this->from);
        }catch(\Exception $e){
            Exception($e->getMessage());
        }
        //封装数据
        $newsInfo = $this->parseCatid($newsInfo);
        $returnData  = [
            "totalCount" => $this->totalCount,
            "totalPages" => $this->totalPages,
            "page" => $this->page,
            "size" => $this->size,
            "title" => empty($data["title"]) ? "" : $data["title"],
            "newInfo" => $newsInfo,
         ];
        return httpResult(config("app.result_ok"),"分页信息",$returnData);
    }
}