<?php
/**
 * 排行相关
 * User: xjyplayer
 * Date: 2018/11/25
 * Time: 15:45
 */

namespace app\api\controller\v1;

use app\api\controller\Common;

class Rank extends Common
{
    protected $myModel;
    public function __construct()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->myModel=model("common/News");
    }

    public function read()
    {
        $data = request()->get();
        if(!empty($data["num"])){
            $num = $data["num"];
        }else{
            $num = 10;
        }
        try{
            $rankInfo = $this->myModel->getRank($num);
        }catch(\Exception $e){
            Exception($e->getMessage());
        }
        //封装数据
        $returnData = [
            "num" => $num,
            "rank" => "read_count => desc",
            "rankInfo" => $rankInfo,
        ];
        return httpResult(config("app.result_ok"),"排行榜",$returnData);
    }
}