<?php
/**点赞功能
 * Created by PhpStorm.
 * User: xjyplayer
 * Date: 2018/11/27
 * Time: 19:22
 */

namespace app\api\controller\v1;

use app\api\controller\AuthBase;

class Upvote extends AuthBase
{
    protected $myModel;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**查询点赞状况
     * @return \think\response\Json
     * @throws \Exception
     */
    public function read()
    {
        $data = request()->get();
        //验证数据
        if(!isset($data["id"])){
            return httpResult(config("app.result_error"),"新闻id错误",[],403);
        }
        //组装查询数据
        $sdata = [
            "news_id" => $data["id"],
            "user_id" => $this->user["id"],
        ];
        //查询是否有数据存在
        try{
            $res = model("common/UserNews")->get($sdata);
        }catch(\Exception $e){
            Exception($e->getFile().$e->getLine().$e->getMessage());
        }
        //返回数据
        if($res){
            $resultData["upvote"] = 1;
            return httpResult(config("app.result_ok"),"点赞状况",$resultData,200);
        }else{
            $resultData["upvote"] = 0;
            return httpResult(config("app.result_ok"),"点赞状况",$resultData,200);
        }
    }

    /**
     * 点赞或者取消点赞
     */
    public function update()
    {
        $data = request()->put();
        //验证数据
        if(!isset($data["id"])){
            return httpResult(config("app.result_error"),"新闻id错误",[],403);
        }
        //组装查询数据
        $sdata = [
            "news_id" => $data["id"],
            "user_id" => $this->user["id"],
        ];
        //查询是否有数据存在
        try{
            $res = model("common/UserNews")->get($sdata);
        }catch(\Exception $e){
            Exception($e->getFile().$e->getLine().$e->getMessage());
        }
        //插入或者删除操作
        if($res){
            $id = $res["id"];
            try{
                $res = model("common/UserNews")->destroy($id,true);
            }catch(\Exception $e){
                Exception($e->getFile().$e->getLine().$e->getMessage());
            }
        }else{
            try{
                $res = model("common/UserNews")->add($sdata);
            }catch(\Exception $e){
                Exception($e->getFile().$e->getLine().$e->getMessage());
            }
        }
        if($res){
            try{
                model("common/News") ->Inc($data["id"],"upvote_count");
            }catch(\Exception $e){
                Exception($e->getFile().$e->getLine().$e->getMessage());
            }
            return httpResult(config("app.result_ok"),"修改状态成功");
        }else{
            try{
                model("common/News") ->Dec($data["id"],"upvote_count");
            }catch(\Exception $e){
                Exception($e->getFile().$e->getLine().$e->getMessage());
            }
            return httpResult(config("app.result_error"),"修改状态失败",[],403);
        }
    }

    /**获取点赞数
     * @return \think\response\Json
     * @throws \Exception
     */
    public function getUpvote()
    {
        $data = request()->get();
        //校验
        if(!isset($data["id"])){
            return httpResult(config("app.result_error"),"id不正确",[],403);
        }
        //查询
        try{
            $res = model("common/News")->get($data["id"]);
        }catch(\Exception $e){
            Exception($e->getFile().$e->getLine().$e->getMessage());
        }
        //校验
        if(empty($res)){
            return httpResult(config("app.result_error"),"新闻不存在",[],404);
        }
        if(!empty($res["upvote_count"])){
            $resultData = [
                "upvote_count" => $res["upvote_count"]
            ];
            return httpResult(config("app.result_ok"),"点赞数量",$resultData);
        }
    }



}